language: node_js
node_js: "6"
sudo: false

env:
  matrix:
    - RUN_SCRIPT=yarn lint && yarn test-worker
    - RUN_SCRIPT=yarn test-lib
    - RUN_SCRIPT=yarn test-api
    - RUN_SCRIPT=yarn test-ui
    - RUN_SCRIPT=npm install pm2 -g && yarn test-integrations && yarn stop-test
  global:
    - MONGODB=3.2.13
    - APP_SECRET=44E52D2227F93179525E252EC3AB5
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - cp .env.example .env
  - cp .env.example .env.test
  - yarn

services:
  - redis-server

before_install:
  - export CXX=g++-4.8
  - export DISPLAY=:99.0
  - export NODE_UNICODETABLE_UNICODEDATA_TXT=$PWD/UnicodeData.txt
  - sh -e /etc/init.d/xvfb start
  - touch .env

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

cache:
  yarn: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - $RUN_SCRIPT

after_script:
  - pkill mongod

