language: node_js
node_js: "6"
sudo: false

env:
  matrix:
    - TEST_SUITE=test-api
    - TEST_SUITE=test-lib
    - TEST_SUITE=test-worker
    - TEST_SUITE=test-ui
  global:
    - MONGODB=3.2.13
    - APP_SECRET=44E52D2227F93179525E252EC3AB5
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - cp .env.example .env
  - cp .env.example .env.test
  - yarn

services:
  - redis-server

before_install:
  - export CXX=g++-4.8
  - export DISPLAY=:99.0
  - export NODE_UNICODETABLE_UNICODEDATA_TXT=$PWD/UnicodeData.txt
  - sh -e /etc/init.d/xvfb start
  - touch .env

before_script:
  - yarn lint
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

cache:
  yarn: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - yarn $TEST_SUITE

jobs:
  - include:
    - stage: start pm2
      script: npm install pm2 -g
    - stage: integration tests
      script: yarn test-integrations
    - stage: stop test instance
      script: yarn stop-test

after_script:
  - pkill mongod

